### PR TITLE
fixes https://github.com/moonstar-x/discord-free-games-notifier/issue…

### PR DESCRIPTION
**Pull request by pironic**
…s/14

### :pencil: Checklist

Make sure that your PR fulfills these requirements:

- [x] Tests have been added for this feature.
- [x] All tests pass on your local machine.
- [x] Code has been linted with the proper rules.

### :page_facing_up: Description

Checks if the discounted price is 0 as well (from epic)

### :pushpin: Does this PR address any issue?

#14

### CODE REVIEW

**Comment by pironic** [comment]
Maybe i should bump the version number too... Got a preference? 2.0.1?

**Comment by moonstar-x** [comment]
Hey there, I was just about to suggest this, I do not have an automatic versioning for this repo.

Could you update the version `2.0.1` in both `package.json` and `package-lock.json`?

**Comment by moonstar-x** [comment]
Hey, your line is a bit too long according to the linter.

I don't mind if you ignore the max-len rule on the entire file.

**Comment by pironic** [comment]
Sorry. My first time with this whole lint thing. Just learning your code style rules :P

**Comment by moonstar-x** [comment]
Inside the `test/classes/providers/EpicGamesProvider.spec.js`, there's an object called `mockedGame`, try adding the `totalPrice: { discountPrice: 0 }` to that object.

You can run tests in your local machine by running: `npm run test:showlogs`

**Pull request merged**
